server:
  port: 8083

spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: 53pazar53+
    url: jdbc:mysql://localhost:3306/unisystem?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
