server:
  port: 8083

spring:
  main:
    banner-mode: off
  datasource:
    username:   /* db username */
    password:   /* db password */
    url:        /* db url */

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
